-- Bootstrap-only SQL — runs via setup-db.mjs (direct Postgres connection)
-- BEFORE `auth:migrate`, so Better Auth's CLI can create its tables in the
-- dedicated `better_auth` schema (lib/auth.ts pins the pool's search_path
-- to `better_auth, public`).
--
-- PostgREST exposes only `public` by default, so anything in `better_auth`
-- is hidden from the data API automatically — no REVOKE block needed. The
-- InsForge dashboard reaches this schema through its admin route (postgres
-- superuser pool), so Studio inspection of users / sessions / accounts /
-- verification still works.
CREATE SCHEMA IF NOT EXISTS better_auth;
